[tool.poetry]
name = "telegram-button-bot"
version = "0.1.0"
description = "Telegram bot with inline label print button"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
aiogram = "3.5.0"
reportlab = "*"
